#!/usr/bin/env python3
"""Generate the narrow Decoder-compatible Unicode XID source.

Input is Unicode's DerivedCoreProperties.txt.  The generated C file exposes
only the Decoder entry points libwgsl needs for WGSL identifiers.
"""

from __future__ import annotations

import argparse
from pathlib import Path


PROPS = ("XID_Start", "XID_Continue")


def parse_ranges(path: Path) -> dict[str, list[tuple[int, int]]]:
    ranges: dict[str, list[tuple[int, int]]] = {name: [] for name in PROPS}
    for line in path.read_text(encoding="utf-8").splitlines():
        body = line.split("#", 1)[0].strip()
        if not body or ";" not in body:
            continue
        span, prop = [part.strip() for part in body.split(";", 1)]
        if prop not in ranges:
            continue
        if ".." in span:
            first_s, last_s = span.split("..", 1)
            first, last = int(first_s, 16), int(last_s, 16)
        else:
            first = last = int(span, 16)
        ranges[prop].append((first, last))
    return ranges


def emit_array(name: str, ranges: list[tuple[int, int]]) -> list[str]:
    lines = [f"static const DecoderRange {name}[] = {{"]
    for first, last in ranges:
        lines.append(f"    {{ 0x{first:06X}u, 0x{last:06X}u }},")
    lines.append("};")
    return lines


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("derived_core_properties", type=Path)
    ap.add_argument("output", type=Path)
    ns = ap.parse_args()

    ranges = parse_ranges(ns.derived_core_properties)
    if not all(ranges.values()):
        raise SystemExit("missing XID ranges in input")

    lines: list[str] = [
        "/* Generated by tools/gen-unicode-xid.py from DerivedCoreProperties-17.0.0.txt.",
        " * Narrow Decoder ABI shim for libwgsl native source builds.",
        " * SPDX-License-Identifier: MIT",
        " */",
        '#include "core.h"',
        '#include "security.h"',
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    uint32_t first;",
        "    uint32_t last;",
        "} DecoderRange;",
        "",
    ]
    lines.extend(emit_array("xid_start_ranges", ranges["XID_Start"]))
    lines.append("")
    lines.extend(emit_array("xid_continue_ranges", ranges["XID_Continue"]))
    lines.extend(
        [
            "",
            "static int range_contains(const DecoderRange *ranges, size_t count, uint32_t cp) {",
            "    size_t lo = 0;",
            "    size_t hi = count;",
            "    while (lo < hi) {",
            "        size_t mid = lo + (hi - lo) / 2;",
            "        if (cp < ranges[mid].first) {",
            "            hi = mid;",
            "        } else if (cp > ranges[mid].last) {",
            "            lo = mid + 1;",
            "        } else {",
            "            return 1;",
            "        }",
            "    }",
            "    return 0;",
            "}",
            "",
            "void decoder_init(void) {}",
            "void decoder_cleanup(void) {}",
            "",
            "const char *decoder_get_unicode_version(void) {",
            "    return DECODER_STANDARD_VERSION;",
            "}",
            "",
            "const char *decoder_error_message(decoder_status_t status) {",
            "    switch (status) {",
            '    case DECODER_SUCCESS: return "success";',
            '    case DECODER_ERROR_INVALID_INPUT: return "invalid input";',
            '    case DECODER_ERROR_BUFFER_TOO_SMALL: return "buffer too small";',
            '    case DECODER_ERROR_INVALID_UTF8: return "invalid UTF-8";',
            '    case DECODER_ERROR_INVALID_UTF16: return "invalid UTF-16";',
            '    case DECODER_ERROR_INVALID_CODEPOINT: return "invalid code point";',
            '    case DECODER_ERROR_OUT_OF_MEMORY: return "out of memory";',
            '    case DECODER_ERROR_NOT_IMPLEMENTED: return "not implemented";',
            '    case DECODER_ERROR_IO: return "I/O error";',
            '    case DECODER_ERROR_INVALID_ARGUMENT: return "invalid argument";',
            '    case DECODER_ERROR_OVERFLOW: return "overflow";',
            '    case DECODER_ERROR_NOT_FOUND: return "not found";',
            '    default: return "unknown error";',
            "    }",
            "}",
            "",
            "bool decoder_is_identifier_start(uint32_t cp) {",
            "    return range_contains(xid_start_ranges,",
            "                          sizeof xid_start_ranges / sizeof xid_start_ranges[0],",
            "                          cp) != 0;",
            "}",
            "",
            "bool decoder_is_identifier_continue(uint32_t cp) {",
            "    return range_contains(xid_continue_ranges,",
            "                          sizeof xid_continue_ranges / sizeof xid_continue_ranges[0],",
            "                          cp) != 0;",
            "}",
            "",
        ]
    )

    ns.output.parent.mkdir(parents=True, exist_ok=True)
    ns.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
