#!/usr/bin/env python3
"""
Generate multi-language bindings from the libwgsl ABI surface.

Single source of truth for `WGSLAbiLayout` field order (must match
`include/wgsl.h` / `wgsl_abi_layout()`).  Emits:

  bindings/python/wgsl_abi.py  — ctypes + runtime layout check
  bindings/rust/abi.rs         — #[repr(C)] layout + extern "C" stubs
  bindings/jni/WGSL.java       — small Java facade over the JNI shim
  bindings/jni/WGSLTest.java   — smoke main for `make test-jni`
  bindings/jni/wgsl_jni.h      — JNI native declarations
  bindings/jni/wgsl_jni.c      — thin JNI adapter to the C ABI

Usage:
  python3 tools/gen-abi-bindings.py
  make gen-abi
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Field order MUST match WGSLAbiLayout in include/wgsl.h.
ABI_U32_FIELDS = [
    "abi_version",
    "ptr_size",
    "diagnostic_size",
    "diagnostic_severity",
    "diagnostic_line",
    "diagnostic_column",
    "diagnostic_end_line",
    "diagnostic_end_column",
    "diagnostic_message",
    "diagnostic_rule",
    "lex_token_size",
    "lex_token_kind",
    "lex_token_offset",
    "lex_token_length",
    "lex_token_line",
    "lex_token_column",
    "hover_size",
    "hover_present",
    "hover_type_repr",
    "hover_signature",
    "hover_doc",
    "hover_symbol_offset",
    "hover_symbol_length",
    "definition_size",
    "definition_present",
    "definition_offset",
    "definition_length",
    "interp_step_cap",
    "interp_buffer_values_cap",
    "interp_max_lanes",
]

# Public POD structs: (C name, fields as (name, c_type_key)).
# c_type_key: i32 | u32 | ptr (const char* / void*)
POD_STRUCTS = {
    "WGSLDiagnostic": [
        ("severity", "i32"),
        ("line", "u32"),
        ("column", "u32"),
        ("end_line", "u32"),
        ("end_column", "u32"),
        ("message", "ptr"),
        ("rule", "ptr"),
    ],
    "WGSLLexToken": [
        ("kind", "i32"),
        ("offset", "u32"),
        ("length", "u32"),
        ("line", "u32"),
        ("column", "u32"),
    ],
    "WGSLHover": [
        ("present", "i32"),
        ("type_repr", "ptr"),
        ("signature", "ptr"),
        ("doc", "ptr"),
        ("symbol_offset", "u32"),
        ("symbol_length", "u32"),
    ],
    "WGSLDefinition": [
        ("present", "i32"),
        ("offset", "u32"),
        ("length", "u32"),
    ],
}

# Core C API for thin wrappers (name, restype, argtypes).
# restype/argtypes use: void | i32 | u32 | ptr | size
API = [
    ("wgsl_init", "void", []),
    ("wgsl_shutdown", "void", []),
    ("wgsl_spec_pin", "ptr", []),
    ("wgsl_unicode_version", "ptr", []),
    ("wgsl_abi_layout", "ptr", []),
    ("wgsl_check", "ptr", ["ptr"]),
    ("wgsl_check_n", "ptr", ["ptr", "size"]),
    ("wgsl_ok", "i32", ["ptr"]),
    ("wgsl_error", "ptr", ["ptr"]),
    ("wgsl_free", "void", ["ptr"]),
    ("wgsl_diagnostic_count", "i32", ["ptr"]),
    ("wgsl_diagnostic", "ptr", ["ptr", "i32"]),
    ("wgsl_module_json", "ptr", ["ptr"]),
    ("wgsl_module_json_len", "size", ["ptr"]),
    ("wgsl_session_new", "ptr", []),
    ("wgsl_session_destroy", "void", ["ptr"]),
    ("wgsl_session_check", "ptr", ["ptr", "ptr"]),
    ("wgsl_free_string", "void", ["ptr"]),
]


def gen_python() -> str:
    fields = ",\n        ".join(f'("{n}", ctypes.c_uint32)' for n in ABI_U32_FIELDS)
    pods = []
    for name, fl in POD_STRUCTS.items():
        fs = []
        for fn, tk in fl:
            ct = {
                "i32": "ctypes.c_int32",
                "u32": "ctypes.c_uint32",
                "ptr": "ctypes.c_void_p",
            }[tk]
            fs.append(f'("{fn}", {ct})')
        pods.append(
            f"class {name}(ctypes.Structure):\n"
            f"    _fields_ = [\n        " + ",\n        ".join(fs) + "\n    ]\n"
        )
    api_lines = []
    typemap = {
        "void": "None",
        "i32": "ctypes.c_int32",
        "u32": "ctypes.c_uint32",
        "ptr": "ctypes.c_void_p",
        "size": "ctypes.c_size_t",
    }
    for name, ret, args in API:
        api_lines.append(f"    lib.{name}.restype = {typemap[ret]}")
        if args:
            alist = ", ".join(typemap[a] for a in args)
            api_lines.append(f"    lib.{name}.argtypes = [{alist}]")
        else:
            api_lines.append(f"    lib.{name}.argtypes = []")

    return f'''\
# AUTO-GENERATED by tools/gen-abi-bindings.py — do not edit by hand.
# Regenerate: make gen-abi
"""
libwgsl Python ctypes bindings (ABI-driven).

Load a shared library built with `make lib-shared` (or your own dylib/so),
then call through the thin wrappers.  Field offsets for public POD structs
are validated against `wgsl_abi_layout()` at load time so LP64/ILP32 stay
honest without hand-copied offsetof tables.
"""
from __future__ import annotations

import ctypes
import os
from typing import Any, Optional, Tuple

ABI_VERSION = 1

class WGSLAbiLayout(ctypes.Structure):
    _fields_ = [
        {fields}
    ]

{chr(10).join(pods)}

def _load_raw(path: str) -> ctypes.CDLL:
    lib = ctypes.CDLL(path)
{chr(10).join(api_lines)}
    return lib


def load(lib_path: Optional[str] = None) -> Tuple[ctypes.CDLL, WGSLAbiLayout]:
    """Load libwgsl and return (cdll, abi_layout).

    Default search: env WGSL_LIB, then .build/libwgsl.dylib / libwgsl.so
    relative to this file's repo root.
    """
    if lib_path is None:
        lib_path = os.environ.get("WGSL_LIB")
    if lib_path is None:
        root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        for name in ("libwgsl.dylib", "libwgsl.so", "libwgsl.dll"):
            cand = os.path.join(root, ".build", name)
            if os.path.isfile(cand):
                lib_path = cand
                break
    if not lib_path or not os.path.isfile(lib_path):
        raise FileNotFoundError(
            "libwgsl shared library not found; build with `make lib-shared` "
            "or set WGSL_LIB=/path/to/libwgsl.dylib"
        )
    lib = _load_raw(lib_path)
    abi_ptr = lib.wgsl_abi_layout()
    if not abi_ptr:
        raise RuntimeError("wgsl_abi_layout returned NULL")
    abi = ctypes.cast(abi_ptr, ctypes.POINTER(WGSLAbiLayout)).contents
    if abi.abi_version != ABI_VERSION:
        raise RuntimeError(
            f"wgsl_abi_layout version {{abi.abi_version}} unsupported "
            f"(want {{ABI_VERSION}})"
        )
    # Cross-check POD sizes against the live layout table.
    if abi.diagnostic_size != ctypes.sizeof(WGSLDiagnostic):
        raise RuntimeError(
            f"WGSLDiagnostic size mismatch: ctypes={{ctypes.sizeof(WGSLDiagnostic)}} "
            f"abi={{abi.diagnostic_size}} (rebuild bindings / check packing)"
        )
    if abi.lex_token_size != ctypes.sizeof(WGSLLexToken):
        raise RuntimeError("WGSLLexToken size mismatch vs wgsl_abi_layout")
    if abi.hover_size != ctypes.sizeof(WGSLHover):
        raise RuntimeError("WGSLHover size mismatch vs wgsl_abi_layout")
    if abi.definition_size != ctypes.sizeof(WGSLDefinition):
        raise RuntimeError("WGSLDefinition size mismatch vs wgsl_abi_layout")
    return lib, abi


class Client:
    """Minimal high-level wrapper around check / diagnostics / module_json."""

    def __init__(self, lib_path: Optional[str] = None):
        self.lib, self.abi = load(lib_path)
        self.lib.wgsl_init()

    def close(self) -> None:
        self.lib.wgsl_shutdown()

    def __enter__(self) -> "Client":
        return self

    def __exit__(self, *args: Any) -> None:
        self.close()

    def spec_pin(self) -> str:
        return ctypes.string_at(self.lib.wgsl_spec_pin()).decode()

    def check(self, src: str) -> "Result":
        p = self.lib.wgsl_check(src.encode("utf-8"))
        return Result(self.lib, p)

    def session_new(self) -> "Session":
        return Session(self.lib, self.lib.wgsl_session_new())


class Result:
    def __init__(self, lib: ctypes.CDLL, ptr: int):
        self._lib = lib
        self._ptr = ptr

    def close(self) -> None:
        if self._ptr:
            self._lib.wgsl_free(self._ptr)
            self._ptr = None

    def __enter__(self) -> "Result":
        return self

    def __exit__(self, *args: Any) -> None:
        self.close()

    @property
    def ok(self) -> bool:
        return bool(self._lib.wgsl_ok(self._ptr))

    @property
    def error(self) -> str:
        p = self._lib.wgsl_error(self._ptr)
        return ctypes.string_at(p).decode() if p else ""

    def diagnostic_count(self) -> int:
        return int(self._lib.wgsl_diagnostic_count(self._ptr))

    def diagnostic(self, index: int) -> WGSLDiagnostic:
        p = self._lib.wgsl_diagnostic(self._ptr, index)
        if not p:
            raise IndexError(index)
        return ctypes.cast(p, ctypes.POINTER(WGSLDiagnostic)).contents

    def module_json(self) -> str:
        p = self._lib.wgsl_module_json(self._ptr)
        return ctypes.string_at(p).decode() if p else ""


class Session:
    def __init__(self, lib: ctypes.CDLL, ptr: int):
        self._lib = lib
        self._ptr = ptr

    def close(self) -> None:
        if self._ptr:
            self._lib.wgsl_session_destroy(self._ptr)
            self._ptr = None

    def __enter__(self) -> "Session":
        return self

    def __exit__(self, *args: Any) -> None:
        self.close()

    def check(self, src: str) -> Result:
        # Session-owned result — do not wgsl_free.
        p = self._lib.wgsl_session_check(self._ptr, src.encode("utf-8"))
        r = Result(self._lib, p)
        r.close = lambda: None  # type: ignore[method-assign]
        return r
'''


def gen_rust() -> str:
    fields = ",\n    ".join(f"pub {n}: u32" for n in ABI_U32_FIELDS)
    pods = []
    for name, fl in POD_STRUCTS.items():
        fs = []
        for fn, tk in fl:
            rt = {"i32": "i32", "u32": "u32", "ptr": "*const std::os::raw::c_char"}[tk]
            if tk == "ptr" and name != "WGSLDiagnostic":
                # hover strings are const char*
                rt = "*const std::os::raw::c_char"
            if tk == "ptr" and fn in ("message", "rule", "type_repr", "signature", "doc"):
                rt = "*const std::os::raw::c_char"
            fs.append(f"    pub {fn}: {rt},")
        # Closing brace must be inside the f-string (`}}` → `}`).  A bare
        # non-f `"\n}}\n"` would emit literal `}}` and break rustc (A2).
        body = "\n".join(fs)
        pods.append(
            f"#[repr(C)]\n"
            f"#[derive(Debug, Copy, Clone)]\n"
            f"pub struct {name} {{\n{body}\n}}\n"
        )

    externs = []
    tmap = {
        "void": "",
        "i32": "-> i32",
        "u32": "-> u32",
        "ptr": "-> *const std::os::raw::c_void",
        "size": "-> usize",
    }
    amap = {
        "i32": "i32",
        "u32": "u32",
        "ptr": "*const std::os::raw::c_void",
        "size": "usize",
    }
    for name, ret, args in API:
        # Specialize a few stringy APIs for ergonomics in the generated stub.
        if name in ("wgsl_check", "wgsl_session_check", "wgsl_spec_pin",
                    "wgsl_unicode_version", "wgsl_error", "wgsl_module_json"):
            continue  # hand-written below
        params = ", ".join(f"a{i}: {amap[t]}" for i, t in enumerate(args))
        ret_s = tmap[ret]
        if ret == "void":
            externs.append(f"    pub fn {name}({params});")
        else:
            externs.append(f"    pub fn {name}({params}) {ret_s};")

    return f'''\
// AUTO-GENERATED by tools/gen-abi-bindings.py — do not edit by hand.
// Regenerate: make gen-abi
//! libwgsl FFI surface (ABI layout + core entry points).
//!
//! Link against `libwgsl` (static or shared).  After load, call
//! [`wgsl_abi_layout`] and check `abi_version == ABI_VERSION`.

#![allow(non_camel_case_types)]

pub const ABI_VERSION: u32 = 1;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WGSLAbiLayout {{
    {fields}
}}

{chr(10).join(pods)}
/// Opaque frontend result (own with [`wgsl_free`]).
pub enum WGSLResult {{}}
/// Opaque incremental session (own with [`wgsl_session_destroy`]).
pub enum WGSLSession {{}}

extern "C" {{
    pub fn wgsl_init();
    pub fn wgsl_shutdown();
    pub fn wgsl_spec_pin() -> *const std::os::raw::c_char;
    pub fn wgsl_unicode_version() -> *const std::os::raw::c_char;
    pub fn wgsl_abi_layout() -> *const WGSLAbiLayout;

    pub fn wgsl_check(src: *const std::os::raw::c_char) -> *mut WGSLResult;
    pub fn wgsl_check_n(src: *const std::os::raw::c_char, src_len: usize) -> *mut WGSLResult;
    pub fn wgsl_ok(r: *const WGSLResult) -> i32;
    pub fn wgsl_error(r: *const WGSLResult) -> *const std::os::raw::c_char;
    pub fn wgsl_free(r: *mut WGSLResult);
    pub fn wgsl_diagnostic_count(r: *const WGSLResult) -> i32;
    pub fn wgsl_diagnostic(r: *const WGSLResult, index: i32) -> *const WGSLDiagnostic;
    pub fn wgsl_module_json(r: *const WGSLResult) -> *const std::os::raw::c_char;
    pub fn wgsl_module_json_len(r: *const WGSLResult) -> usize;

    pub fn wgsl_session_new() -> *mut WGSLSession;
    pub fn wgsl_session_destroy(s: *mut WGSLSession);
    pub fn wgsl_session_check(
        s: *mut WGSLSession,
        src: *const std::os::raw::c_char,
    ) -> *const WGSLResult;

    pub fn wgsl_free_string(s: *mut std::os::raw::c_char);
}}
'''


def gen_jni_java() -> str:
    return '''\
// AUTO-GENERATED by tools/gen-abi-bindings.py - do not edit by hand.
// Regenerate: make gen-abi

import java.nio.charset.StandardCharsets;
import java.util.Objects;

/** Minimal JNI facade over libwgsl's C ABI. */
public final class WGSL {
    private WGSL() {}

    static {
        System.loadLibrary("wgsl_jni");
        assertAbi();
        initNative();
    }

    private static native void assertAbi();
    private static native void initNative();
    private static native void shutdownNative();
    private static native long checkNative(byte[] utf8);
    private static native boolean okNative(long ptr);
    private static native String errorNative(long ptr);
    private static native int diagnosticCountNative(long ptr);
    private static native Diagnostic diagnosticNative(long ptr, int index);
    private static native void freeNative(long ptr);

    public static void shutdown() {
        shutdownNative();
    }

    public static Result check(String source) {
        Objects.requireNonNull(source, "source");
        return new Result(checkNative(source.getBytes(StandardCharsets.UTF_8)));
    }

    public record Diagnostic(
        int severity,
        int line,
        int column,
        int endLine,
        int endColumn,
        String message,
        String rule
    ) {}

    public static final class Result implements AutoCloseable {
        private long ptr;

        private Result(long ptr) {
            if (ptr == 0) {
                throw new IllegalStateException("wgsl_check returned NULL");
            }
            this.ptr = ptr;
        }

        public boolean ok() {
            return okNative(livePtr());
        }

        public String error() {
            return errorNative(livePtr());
        }

        public int diagnosticCount() {
            return diagnosticCountNative(livePtr());
        }

        public Diagnostic diagnostic(int index) {
            return diagnosticNative(livePtr(), index);
        }

        private long livePtr() {
            if (ptr == 0) {
                throw new IllegalStateException("WGSL.Result is closed");
            }
            return ptr;
        }

        @Override
        public void close() {
            if (ptr != 0) {
                freeNative(ptr);
                ptr = 0;
            }
        }
    }
}
'''


def gen_jni_test_java() -> str:
    return '''\
// AUTO-GENERATED by tools/gen-abi-bindings.py - do not edit by hand.
// Regenerate: make gen-abi

public final class WGSLTest {
    private static int failures;

    private static void check(boolean condition, String message) {
        if (!condition) {
            failures++;
            System.err.println("FAIL  " + message);
        }
    }

    public static void main(String[] args) {
        try (WGSL.Result ok = WGSL.check("fn f() {}\\n")) {
            check(ok.ok(), "valid WGSL checks");
            check(ok.diagnosticCount() == 0, "valid WGSL has no diagnostics");
        }

        try (WGSL.Result bad = WGSL.check("fn f() { var x: i32 = true; }\\n")) {
            check(!bad.ok(), "invalid WGSL rejected");
            check(bad.diagnosticCount() > 0, "invalid WGSL has diagnostics");
            WGSL.Diagnostic d = bad.diagnostic(0);
            check(d.message() != null && !d.message().isEmpty(),
                  "diagnostic message non-empty");
            System.out.println("JNI diagnostic: " + d.message());
        }

        WGSL.shutdown();
        System.err.printf("%s  test_jni  (%d failure%s)%n",
                          failures == 0 ? "PASS" : "FAIL",
                          failures,
                          failures == 1 ? "" : "s");
        if (failures != 0) {
            System.exit(1);
        }
    }
}
'''


def gen_jni_header() -> str:
    return '''\
/* AUTO-GENERATED by tools/gen-abi-bindings.py - do not edit by hand.
 * Regenerate: make gen-abi
 */
#ifndef WGSL_JNI_H
#define WGSL_JNI_H

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_WGSL_assertAbi(JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_WGSL_initNative(JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_WGSL_shutdownNative(JNIEnv *, jclass);
JNIEXPORT jlong JNICALL Java_WGSL_checkNative(JNIEnv *, jclass, jbyteArray);
JNIEXPORT jboolean JNICALL Java_WGSL_okNative(JNIEnv *, jclass, jlong);
JNIEXPORT jstring JNICALL Java_WGSL_errorNative(JNIEnv *, jclass, jlong);
JNIEXPORT jint JNICALL Java_WGSL_diagnosticCountNative(JNIEnv *, jclass, jlong);
JNIEXPORT jobject JNICALL Java_WGSL_diagnosticNative(JNIEnv *, jclass, jlong, jint);
JNIEXPORT void JNICALL Java_WGSL_freeNative(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif

#endif /* WGSL_JNI_H */
'''


def gen_jni_c() -> str:
    return '''\
/* AUTO-GENERATED by tools/gen-abi-bindings.py - do not edit by hand.
 * Regenerate: make gen-abi
 */
#include "wgsl_jni.h"

#include "wgsl.h"

#include <stdint.h>
#include <string.h>

static void throw_by_name(JNIEnv *env, const char *class_name, const char *msg) {
    jclass cls = (*env)->FindClass(env, class_name);
    if (cls) (*env)->ThrowNew(env, cls, msg);
}

static WGSLResult *as_result(jlong ptr) {
    return (WGSLResult *)(uintptr_t)ptr;
}

static jstring to_jstring(JNIEnv *env, const char *s) {
    return (*env)->NewStringUTF(env, s ? s : "");
}

JNIEXPORT void JNICALL Java_WGSL_assertAbi(JNIEnv *env, jclass cls) {
    (void)cls;
    const WGSLAbiLayout *abi = wgsl_abi_layout();
    if (!abi) {
        throw_by_name(env, "java/lang/IllegalStateException",
                      "wgsl_abi_layout returned NULL");
        return;
    }
    if (abi->abi_version != 1u || abi->ptr_size != (uint32_t)sizeof(void *) ||
        abi->diagnostic_size != (uint32_t)sizeof(WGSLDiagnostic))
    {
        throw_by_name(env, "java/lang/IllegalStateException",
                      "libwgsl ABI layout mismatch");
    }
}

JNIEXPORT void JNICALL Java_WGSL_initNative(JNIEnv *env, jclass cls) {
    (void)env;
    (void)cls;
    wgsl_init();
}

JNIEXPORT void JNICALL Java_WGSL_shutdownNative(JNIEnv *env, jclass cls) {
    (void)env;
    (void)cls;
    wgsl_shutdown();
}

JNIEXPORT jlong JNICALL Java_WGSL_checkNative(
    JNIEnv *env, jclass cls, jbyteArray src)
{
    (void)cls;
    if (!src) {
        throw_by_name(env, "java/lang/NullPointerException", "source");
        return 0;
    }
    jsize len = (*env)->GetArrayLength(env, src);
    jbyte *bytes = (*env)->GetByteArrayElements(env, src, NULL);
    if (!bytes) return 0;
    WGSLResult *r = wgsl_check_n((const char *)bytes, (size_t)len);
    (*env)->ReleaseByteArrayElements(env, src, bytes, JNI_ABORT);
    return (jlong)(uintptr_t)r;
}

JNIEXPORT jboolean JNICALL Java_WGSL_okNative(JNIEnv *env, jclass cls, jlong ptr) {
    (void)env;
    (void)cls;
    return wgsl_ok(as_result(ptr)) ? JNI_TRUE : JNI_FALSE;
}

JNIEXPORT jstring JNICALL Java_WGSL_errorNative(JNIEnv *env, jclass cls, jlong ptr) {
    (void)cls;
    return to_jstring(env, wgsl_error(as_result(ptr)));
}

JNIEXPORT jint JNICALL Java_WGSL_diagnosticCountNative(
    JNIEnv *env, jclass cls, jlong ptr)
{
    (void)env;
    (void)cls;
    return (jint)wgsl_diagnostic_count(as_result(ptr));
}

JNIEXPORT jobject JNICALL Java_WGSL_diagnosticNative(
    JNIEnv *env, jclass cls, jlong ptr, jint index)
{
    (void)cls;
    const WGSLDiagnostic *d = wgsl_diagnostic(as_result(ptr), (int)index);
    if (!d) {
        throw_by_name(env, "java/lang/IndexOutOfBoundsException",
                      "diagnostic index out of range");
        return NULL;
    }

    jclass diag_cls = (*env)->FindClass(env, "WGSL$Diagnostic");
    if (!diag_cls) return NULL;
    jmethodID ctor = (*env)->GetMethodID(
        env, diag_cls, "<init>", "(IIIIILjava/lang/String;Ljava/lang/String;)V");
    if (!ctor) return NULL;

    jstring msg = to_jstring(env, d->message);
    if (!msg) return NULL;
    jstring rule = to_jstring(env, d->rule);
    if (!rule) return NULL;

    return (*env)->NewObject(
        env, diag_cls, ctor,
        (jint)d->severity,
        (jint)d->line,
        (jint)d->column,
        (jint)d->end_line,
        (jint)d->end_column,
        msg,
        rule);
}

JNIEXPORT void JNICALL Java_WGSL_freeNative(JNIEnv *env, jclass cls, jlong ptr) {
    (void)env;
    (void)cls;
    wgsl_free(as_result(ptr));
}
'''


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify generated files are up to date (no write)",
    )
    args = ap.parse_args()

    py_path = ROOT / "bindings" / "python" / "wgsl_abi.py"
    rs_path = ROOT / "bindings" / "rust" / "abi.rs"
    jni_java_path = ROOT / "bindings" / "jni" / "WGSL.java"
    jni_test_path = ROOT / "bindings" / "jni" / "WGSLTest.java"
    jni_h_path = ROOT / "bindings" / "jni" / "wgsl_jni.h"
    jni_c_path = ROOT / "bindings" / "jni" / "wgsl_jni.c"
    py = gen_python()
    rs = gen_rust()
    jni_java = gen_jni_java()
    jni_test = gen_jni_test_java()
    jni_h = gen_jni_header()
    jni_c = gen_jni_c()

    generated = [
        (py_path, py),
        (rs_path, rs),
        (jni_java_path, jni_java),
        (jni_test_path, jni_test),
        (jni_h_path, jni_h),
        (jni_c_path, jni_c),
    ]

    if args.check:
        ok = True
        for path, content in generated:
            if not path.is_file() or path.read_text() != content:
                print(f"OUT OF DATE: {path}")
                ok = False
        if not ok:
            raise SystemExit(1)
        print("gen-abi-bindings: up to date")
        return

    for path, content in generated:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
