/* AUTO-GENERATED by tools/gen-abi-bindings.py - do not edit by hand.
 * Regenerate: make gen-abi
 */
#include "wgsl_jni.h"

#include "wgsl.h"

#include <stdint.h>
#include <string.h>

static void throw_by_name(JNIEnv *env, const char *class_name, const char *msg) {
    jclass cls = (*env)->FindClass(env, class_name);
    if (cls) (*env)->ThrowNew(env, cls, msg);
}

static WGSLResult *as_result(jlong ptr) {
    return (WGSLResult *)(uintptr_t)ptr;
}

static jstring to_jstring(JNIEnv *env, const char *s) {
    return (*env)->NewStringUTF(env, s ? s : "");
}

JNIEXPORT void JNICALL Java_WGSL_assertAbi(JNIEnv *env, jclass cls) {
    (void)cls;
    const WGSLAbiLayout *abi = wgsl_abi_layout();
    if (!abi) {
        throw_by_name(env, "java/lang/IllegalStateException",
                      "wgsl_abi_layout returned NULL");
        return;
    }
    if (abi->abi_version != 1u || abi->ptr_size != (uint32_t)sizeof(void *) ||
        abi->diagnostic_size != (uint32_t)sizeof(WGSLDiagnostic))
    {
        throw_by_name(env, "java/lang/IllegalStateException",
                      "libwgsl ABI layout mismatch");
    }
}

JNIEXPORT void JNICALL Java_WGSL_initNative(JNIEnv *env, jclass cls) {
    (void)env;
    (void)cls;
    wgsl_init();
}

JNIEXPORT void JNICALL Java_WGSL_shutdownNative(JNIEnv *env, jclass cls) {
    (void)env;
    (void)cls;
    wgsl_shutdown();
}

JNIEXPORT jlong JNICALL Java_WGSL_checkNative(
    JNIEnv *env, jclass cls, jbyteArray src)
{
    (void)cls;
    if (!src) {
        throw_by_name(env, "java/lang/NullPointerException", "source");
        return 0;
    }
    jsize len = (*env)->GetArrayLength(env, src);
    jbyte *bytes = (*env)->GetByteArrayElements(env, src, NULL);
    if (!bytes) return 0;
    WGSLResult *r = wgsl_check_n((const char *)bytes, (size_t)len);
    (*env)->ReleaseByteArrayElements(env, src, bytes, JNI_ABORT);
    return (jlong)(uintptr_t)r;
}

JNIEXPORT jboolean JNICALL Java_WGSL_okNative(JNIEnv *env, jclass cls, jlong ptr) {
    (void)env;
    (void)cls;
    return wgsl_ok(as_result(ptr)) ? JNI_TRUE : JNI_FALSE;
}

JNIEXPORT jstring JNICALL Java_WGSL_errorNative(JNIEnv *env, jclass cls, jlong ptr) {
    (void)cls;
    return to_jstring(env, wgsl_error(as_result(ptr)));
}

JNIEXPORT jint JNICALL Java_WGSL_diagnosticCountNative(
    JNIEnv *env, jclass cls, jlong ptr)
{
    (void)env;
    (void)cls;
    return (jint)wgsl_diagnostic_count(as_result(ptr));
}

JNIEXPORT jobject JNICALL Java_WGSL_diagnosticNative(
    JNIEnv *env, jclass cls, jlong ptr, jint index)
{
    (void)cls;
    const WGSLDiagnostic *d = wgsl_diagnostic(as_result(ptr), (int)index);
    if (!d) {
        throw_by_name(env, "java/lang/IndexOutOfBoundsException",
                      "diagnostic index out of range");
        return NULL;
    }

    jclass diag_cls = (*env)->FindClass(env, "WGSL$Diagnostic");
    if (!diag_cls) return NULL;
    jmethodID ctor = (*env)->GetMethodID(
        env, diag_cls, "<init>", "(IIIIILjava/lang/String;Ljava/lang/String;)V");
    if (!ctor) return NULL;

    jstring msg = to_jstring(env, d->message);
    if (!msg) return NULL;
    jstring rule = to_jstring(env, d->rule);
    if (!rule) return NULL;

    return (*env)->NewObject(
        env, diag_cls, ctor,
        (jint)d->severity,
        (jint)d->line,
        (jint)d->column,
        (jint)d->end_line,
        (jint)d->end_column,
        msg,
        rule);
}

JNIEXPORT void JNICALL Java_WGSL_freeNative(JNIEnv *env, jclass cls, jlong ptr) {
    (void)env;
    (void)cls;
    wgsl_free(as_result(ptr));
}
