// AUTO-GENERATED by tools/gen-abi-bindings.py - do not edit by hand.
// Regenerate: make gen-abi

public final class WGSLTest {
    private static int failures;

    private static void check(boolean condition, String message) {
        if (!condition) {
            failures++;
            System.err.println("FAIL  " + message);
        }
    }

    public static void main(String[] args) {
        try (WGSL.Result ok = WGSL.check("fn f() {}\n")) {
            check(ok.ok(), "valid WGSL checks");
            check(ok.diagnosticCount() == 0, "valid WGSL has no diagnostics");
        }

        try (WGSL.Result bad = WGSL.check("fn f() { var x: i32 = true; }\n")) {
            check(!bad.ok(), "invalid WGSL rejected");
            check(bad.diagnosticCount() > 0, "invalid WGSL has diagnostics");
            WGSL.Diagnostic d = bad.diagnostic(0);
            check(d.message() != null && !d.message().isEmpty(),
                  "diagnostic message non-empty");
            System.out.println("JNI diagnostic: " + d.message());
        }

        WGSL.shutdown();
        System.err.printf("%s  test_jni  (%d failure%s)%n",
                          failures == 0 ? "PASS" : "FAIL",
                          failures,
                          failures == 1 ? "" : "s");
        if (failures != 0) {
            System.exit(1);
        }
    }
}
