// AUTO-GENERATED by tools/gen-abi-bindings.py - do not edit by hand.
// Regenerate: make gen-abi

import java.nio.charset.StandardCharsets;
import java.util.Objects;

/** Minimal JNI facade over libwgsl's C ABI. */
public final class WGSL {
    private WGSL() {}

    static {
        System.loadLibrary("wgsl_jni");
        assertAbi();
        initNative();
    }

    private static native void assertAbi();
    private static native void initNative();
    private static native void shutdownNative();
    private static native long checkNative(byte[] utf8);
    private static native boolean okNative(long ptr);
    private static native String errorNative(long ptr);
    private static native int diagnosticCountNative(long ptr);
    private static native Diagnostic diagnosticNative(long ptr, int index);
    private static native void freeNative(long ptr);

    public static void shutdown() {
        shutdownNative();
    }

    public static Result check(String source) {
        Objects.requireNonNull(source, "source");
        return new Result(checkNative(source.getBytes(StandardCharsets.UTF_8)));
    }

    public record Diagnostic(
        int severity,
        int line,
        int column,
        int endLine,
        int endColumn,
        String message,
        String rule
    ) {}

    public static final class Result implements AutoCloseable {
        private long ptr;

        private Result(long ptr) {
            if (ptr == 0) {
                throw new IllegalStateException("wgsl_check returned NULL");
            }
            this.ptr = ptr;
        }

        public boolean ok() {
            return okNative(livePtr());
        }

        public String error() {
            return errorNative(livePtr());
        }

        public int diagnosticCount() {
            return diagnosticCountNative(livePtr());
        }

        public Diagnostic diagnostic(int index) {
            return diagnosticNative(livePtr(), index);
        }

        private long livePtr() {
            if (ptr == 0) {
                throw new IllegalStateException("WGSL.Result is closed");
            }
            return ptr;
        }

        @Override
        public void close() {
            if (ptr != 0) {
                freeNative(ptr);
                ptr = 0;
            }
        }
    }
}
