/* AUTO-GENERATED by tools/gen-abi-bindings.py - do not edit by hand.
 * Regenerate: make gen-abi
 */
#ifndef WGSL_JNI_H
#define WGSL_JNI_H

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_WGSL_assertAbi(JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_WGSL_initNative(JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_WGSL_shutdownNative(JNIEnv *, jclass);
JNIEXPORT jlong JNICALL Java_WGSL_checkNative(JNIEnv *, jclass, jbyteArray);
JNIEXPORT jboolean JNICALL Java_WGSL_okNative(JNIEnv *, jclass, jlong);
JNIEXPORT jstring JNICALL Java_WGSL_errorNative(JNIEnv *, jclass, jlong);
JNIEXPORT jint JNICALL Java_WGSL_diagnosticCountNative(JNIEnv *, jclass, jlong);
JNIEXPORT jobject JNICALL Java_WGSL_diagnosticNative(JNIEnv *, jclass, jlong, jint);
JNIEXPORT void JNICALL Java_WGSL_freeNative(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif

#endif /* WGSL_JNI_H */
